const sampleMovies = [
    {
        name: "Pulp Fiction",
        director: "Quentin Tarantino",
        genres: "Crime, Drama",
        description: "La vida de dos sicarios de la mafia, un boxeador, un gángster y su esposa, y una pareja de asaltantes de cafeterías se entrelazan en cuatro historias de violencia y redención.",
        duration: 154, 
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481607/trailers/lj6i2daebvzjypemoxzi.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481685/trailers/ffl00y1xeda7snkjfee8.mp4",
        userId:3
    },
    {
        name: "Matrix",
        director: "Lana Wachowski, Lilly Wachowski",
        genres: "Action, Science Fiction",
        description: "Un hacker informático descubre, gracias a unos rebeldes misteriosos, la verdadera naturaleza de su realidad y su papel en la guerra contra quienes la controlan.",
        duration: 136,
        country: "United States",
        poster: "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481608/movies/yeavhvtaaixdgrbmjzji.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481686/movies/fwdnfrum84epvy27licn.mp4",
        userId:3
    },
    {
        name: "Forrest Gump",
        director: "Robert Zemeckis",
        genres: "Drama, Romance",
        description: "Las presidencias de Kennedy y Johnson, los eventos de Vietnam, Watergate, y otros sucesos históricos se desarrollan desde la perspectiva de un hombre de Alabama con un coeficiente intelectual de 75, cuyo único deseo es reencontrarse con su novia de la infancia.",
        duration: 142, 
        country: "United States",
        poster: "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711482111/movies/t5qwv1lxuv34n608rcbg.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481958/movies/mbwjnhvu2iueltsi9lcq.mp4",
        userId:3
    },
    {
        name: "El Señor de los Anillos: La Comunidad del Anillo",
        director: "Peter Jackson",
        genres: "Action, Adventure, Drama",
        description: "Un Hobbit tímido de la Comarca, junto a ocho compañeros, emprende un viaje para destruir el poderoso Anillo Único y salvar a la Tierra Media del Señor Oscuro Sauron.",
        duration: 178,
        country: "United States",
        poster: "https://pics.filmaffinity.com/El_seanor_de_los_anillos_La_comunidad_del_anillo-744631610-large.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481957/trailers/wmmjmiks0cqfzayr6kbj.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711482110/trailers/zwqqv8zb9v7nwgxn5jp9.mp4",
        userId:3
    },
    {
        name: "Malditos Bastardos",
        director: "Quentin Tarantino",
        genres: "Adventure, Drama, War",
        description: "En la Francia ocupada por los nazis durante la Segunda Guerra Mundial, un grupo de soldados judíos de EE. UU. se embarca en una misión para asesinar a los líderes nazis. Sus planes coinciden con los de una dueña de cine que busca venganza por la muerte de su familia.",
        duration: 153, 
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/dqu7nUtKTLdpM7DaJvD4zcSXhn1.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        userId:3
    },
    {
        name: "Milagros inesperados",
        director: "Frank Darabont",
        genres: "Crime, Drama, Fantasy",
        description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
        duration: 189,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/fbrKZSm8Pkhll5e1tYosh56FajT.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "El Padrino: Parte II",
        director: "Francis Ford Coppola",
        genres: "Crime, Drama",
        description: "Se muestra la juventud y el inicio de la carrera de Vito Corleone en la ciudad de Nueva York durante los años 20, al mismo tiempo que su hijo, Michael, expande y consolida su control sobre el imperio criminal familiar.",
        duration: 202,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "La lista de Schindler",
        director: "Steven Spielberg",
        genres: "Biography, Drama, History",
        description: "En la Polonia ocupada por los alemanes durante la Segunda Guerra Mundial, el industrial Oskar Schindler se va preocupando cada vez más por sus trabajadores judíos al ser testigo de la persecución que sufren a manos de los nazis.",
        duration: 195,
        country: "United States",
        poster: "https://es.web.img2.acsta.net/pictures/14/02/27/09/35/442750.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "El Rey Leon",
        director: "Roger Allers, Rob Minkoff",
        genres: "Animation, Adventure, Drama",
        description: "El cachorro de león y futuro rey Simba busca su identidad. Su entusiasmo por complacer a los demás y su tendencia a poner a prueba los límites a veces lo mete en problemas.",
        duration: 89,
        country: "United States",
        poster: "https://i.pinimg.com/originals/af/42/6d/af426df437acda0333fc53a806d5514f.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Batman: El Caballero de la Noche",
        director: "Christopher Nolan",
        genres: "Action, Crime, Drama",
        description: "Cuando el maníaco conocido como el Guasón desata el caos y la destrucción sobre los ciudadanos de Gotham, Batman se enfrenta a una de las pruebas más grandes, tanto física como psicológica, de su capacidad para luchar por la justicia.",
        duration: 152,
        country: "United States",
        poster: "https://i.pinimg.com/originals/09/26/f5/0926f5f1b0f1eceb9c0d7a74cab63e8e.png",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "Toy Story",
        director: "John Lasseter",
        genres: "Animation, Adventure, Comedy",
        description: "Un vaquero de juguete se siente profundamente amenazado y celoso cuando un nuevo astronauta lo reemplaza como el juguete favorito del niño en la habitación.",
        duration: 81,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "El Padrino",
        director: "Francis Ford Coppola",
        genres: "Crime, Drama",
        description: "El anciano patriarca de un imperio del crimen organizado cede el control de su red clandestina a su hijo reacio.",
        duration: 175,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Avatar",
        director: "James Cameron",
        genres: "Action, Adventure, Fantasy",
        description: "Un marine parapléjico es enviado a la luna Pandora en una misión especial. Allí, se debate entre cumplir sus órdenes y proteger el mundo que siente como su hogar.",
        duration: 162,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "Interstellar",
        director: "Christopher Nolan",
        genres: "Adventure, Drama, Science Fiction",
        description: "Un equipo de exploradores atraviesa un agujero de gusano en el espacio en un intento por asegurar la supervivencia de la humanidad.",
        duration: 169,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Ratatouille",
        director: "Brad Bird",
        genres: "Animation, Comedy, Family",
        description: "Un rata con un don especial para la cocina forma una alianza inesperada con un joven ayudante de cocina en un famoso restaurante.",
        duration: 111,
        country: "United States",
        poster: "https://m.media-amazon.com/images/I/71AgTmoFdEL._AC_UF894,1000_QL80_.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Amélie",
        director: "Jean-Pierre Jeunet",
        genres: "Comedy, Romance",
        description: "Amélie es una joven parisina inocente y soñadora con un particular sentido de la justicia. Decide intervenir discretamente en la vida de las personas que la rodean para mejorarlas, embarcándose en un viaje de inesperadas consecuencias que la llevará a descubrir el amor.",
        duration: 122,
        country: "France",
        poster: "https://image.tmdb.org/t/p/original/mYvUib00miJWxWkiXhy3QnrCj96.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Sueños de Fuga",
        director: "Frank Darabont",
        genres: "Drama",
        description: "Dos hombres encarcelados forman un vínculo a lo largo de varios años, encontrando consuelo y una eventual redención a través de actos de simple humanidad.",
        duration: 142,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/9tDQP1b1iffUP9gj1YCinNX3AcZ.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Club de la Lucha",
        director: "David Fincher",
        genres: "Drama",
        description: "Un oficinista insomne y un fabricante de jabones despreocupado forman un club de lucha clandestino que se transforma en algo mucho más grande.",
        duration: 139,
        country: "United States",
        poster: "https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "El silencio de los inocentes",
        director: "Jonathan Demme",
        genres: "Crime, Drama, Thriller",
        description: "Una joven cadete del FBI debe recurrir a la ayuda de un asesino caníbal encarcelado y manipulador para atrapar a otro asesino en serie, un loco que desuella a sus víctimas.",
        duration: 118,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/9OotAIqASfWZES2xsZiHhfi2qm5.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Your Name",
        director: "Makoto Shinkai",
        genres: "Animation, Drama, Fantasy, Romance",
        description: "Mitsuha, una chica de campo, y Taki, un chico de Tokio, intercambian cuerpos de forma esporádica. Su conexión se profundiza a medida que anhelan encontrarse, tras la caída de dos estrellas.",
        duration: 107,
        country: "Japan",
        poster: "https://m.media-amazon.com/images/M/MV5BNGYyNmI3M2YtNzYzZS00OTViLTkxYjAtZDIyZmE1Y2U1ZmQ2XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "El truco final",
        director: "Christopher Nolan",
        genres: "Drama, Mystery, Science Fiction",
        description: "Dos magos de escenario se enfrascan en una feroz competencia para crear la ilusión definitiva. Su rivalidad los lleva a un duelo constante, superándose el uno al otro con trucos cada vez más audaces y deslumbrantes.",
        duration: 130,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/lIl2CrnWohGrZSO9eyKRptxZ7Hs.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Eterno resplandor de una mente sin recuerdos",
        director: "Michel Gondry",
        genres: "Drama, Romance, Science Fiction",
        description: "Cuando su relación se deteriora, una pareja se somete a un procedimiento médico para borrarse mutuamente de sus recuerdos.",
        duration: 108,
        country: "United States",
        poster: "https://m.media-amazon.com/images/M/MV5BMjg0ZmVmZjYtNWVjZC00MjM5LThkYTItMmVjOGE3Mjc3ZGNjXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_FMjpg_UX1000_.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Ciudad de Dios",
        director: "Fernando Meirelles, Kátia Lund",
        genres: "Crime, Drama",
        description: "En las favelas de Río, los caminos de dos jóvenes divergen: uno lucha por convertirse en fotógrafo, mientras el otro se hunde en el crimen para convertirse en capo.",
        duration: 130,
        country: "Brazil",
        poster: "https://image.tmdb.org/t/p/original/2MztAexSbCVszezV0bKMKZPJAZf.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "El gran hotel Budapest",
        director: "Wes Anderson",
        genres: "Adventure, Comedy, Crime",
        description: "El escritor se encontró con el dueño de un hotel antiguo y decadente. El hombre, nostálgico, le habló de su juventud como botones del hotel en sus años gloriosos, cuando estaba bajo la tutela de un conserje excepcional.",
        duration: 99,
        country: "United States",
        poster: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Los infiltrados",
        director: "Martin Scorsese",
        genres: "Crime, Drama, Thriller",
        description: "Un policía encubierto y un topo infiltrado en la policía intentan descubrir la identidad del otro mientras se adentran en una peligrosa operación para acabar con una mafia irlandesa en el sur de Boston.",
        duration: 151,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/qYbry0wFt5ZPJtc53PmB42d0Qqq.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Inception",
        director: "Christopher Nolan",
        genres: "Action, Adventure, Science Fiction",
        description: "Un ladrón que se infiltra en los sueños de las personas para robar sus secretos tiene la oportunidad de redimirse cuando le ofrecen un trabajo inusual: implantar una idea en la mente de un director ejecutivo.",
        duration: 148,
        country: "United States",
        poster: "https://m.media-amazon.com/images/I/71DwIcSgFcS.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "Mente indomable",
        director: "Gus Van Sant",
        genres: "Drama, Romance",
        description: "Will Hunting, un conserje del M.I.T, tiene un talento innato para las matemáticas. Sin embargo, necesita la ayuda de un psicólogo para encontrar un rumbo en su vida.",
        duration: 126,
        country: "United States",
        poster: "https://i.pinimg.com/736x/79/2e/5c/792e5cb387919357ff527b6b67f60a63.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "El show de Truman",
        director: "Peter Weir",
        genres: "Comedy, Drama, Science Fiction",
        description: "Su vida aparentemente normal se derrumba cuando un vendedor de seguros descubre que es la estrella involuntaria de un reality show.",
        duration: 103,
        country: "United States",
        poster: "https://images.justwatch.com/poster/76810863/s718/el-show-de-truman.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "Spirit",
        director: "Kelly Asbury, Lorna Cook",
        genres: "Animation, Adventure, Family",
        description: "Un semental salvaje es capturado por los humanos y, aunque lentamente va perdiendo el ímpetu de resistir el entrenamiento, la esperanza de volver algún día con su manada lo mantiene en pie a lo largo de sus luchas por la libertad.",
        duration: 83,
        country: "United States",
        poster: "https://m.media-amazon.com/images/I/61Xwd30pi6L._AC_UF894,1000_QL80_.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "Whiplash",
        director: "Damien Chazelle",
        genres: "Drama, Music",
        description: "Un joven baterista con un futuro brillante ingresa a un conservatorio de música de altísima competencia. Allí, sus sueños de grandeza serán guiados por un instructor implacable que no se detendrá ante nada para sacar el máximo potencial de sus alumnos.",
        duration: 106,
        country: "United States",
        poster: "https://m.media-amazon.com/images/I/61PwPadu4-L._AC_UF894,1000_QL80_.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4"
    },
    {
        name: "La La Land",
        director: "Damien Chazelle",
        genres: "Comedy, Drama, Music",
        description: "Mientras persiguen sus sueños en Los Ángeles, un pianista y una actriz se enamoran. Sin embargo, su amor se enfrenta al desafío de reconciliar sus aspiraciones para el futuro.",
        duration: 128,
        country: "United States",
        poster: "https://m.media-amazon.com/images/I/816O+CBx0ML.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "Coco",
        director: "Lee Unkrich",
        genres: "Animation, Adventure, Family",
        description: "Miguel, un joven con un gran sueño de ser músico, se enfrenta a una antigua prohibición familiar: ¡la música está vedada! Decidido a romper la tradición y encontrar su destino, Miguel se adentra en la colorida y sorprendente Tierra de los Muertos. Allí, emprende una búsqueda para encontrar a su tatarabuelo, ¡un legendario cantante!",
        duration: 105,
        country: "United States",
        poster: "https://m.media-amazon.com/images/I/817aStLW2rL._AC_UF894,1000_QL80_.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711218456/movies/prnsgwdtbqoqsfuwtegy.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "Demon Slayer: El tren infinito",
        director: "Haruo Sotozaki",
        genres: "Animation, Action, Adventure",
        description: "Tanjiro, Inosuke y Zenitsu se unen al Pilar de la Llama, Kyojuro Rengoku, para abordar el Tren Infinito y derrotar a un demonio que aterroriza y asesina a cazadores de demonios.",
        duration: 117,
        country: "Japan",
        poster: "https://m.media-amazon.com/images/M/MV5BMGU5NjkyNTctYTNlYi00NDFiLTgzZWYtNThjYTQ2MDZmNTNjXkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481607/trailers/lj6i2daebvzjypemoxzi.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481685/trailers/ffl00y1xeda7snkjfee8.mp4"
    },
    {
        name: "Misión Imposible",
        director: "Brian De Palma",
        genres: "Action, Adventure, Thriller",
        description: "Un agente estadounidense, acusado falsamente de deslealtad, debe descubrir y desenmascarar al verdadero espía sin la ayuda de su organización.",
        duration: 110,
        country: "United States",
        poster: "https://filmartgallery.com/cdn/shop/products/Mission-Impossible-Vintage-Movie-Poster-Original-1-Sheet-27x41_ae1e1e64-23cb-45fd-a8dc-bb6625e01daf.jpg?v=1663224951",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481607/trailers/lj6i2daebvzjypemoxzi.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711659864/movies/fowpqfklyfq08faycse9.mp4"
    },
    {
        name: "Estación Zombie",
        director: "Sang-ho Yeon",
        genres: "Action, Horror, Thriller",
        description: "Un brote de un virus zombie azota a Corea del Sur. Los pasajeros del tren bala de Seúl a Busan luchan por sobrevivir en su viaje.",
        duration: 118,
        country: "South Korea",
        poster: "https://image.tmdb.org/t/p/original/gQDPQxUNep5TPgFPRRORAWFQueQ.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481607/trailers/lj6i2daebvzjypemoxzi.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481685/trailers/ffl00y1xeda7snkjfee8.mp4"
    },
    {
        name: "La Exorcista",
        director: "David Gordon Green",
        genres: "Drama, Horror",
        description: "Una madre soltera busca la ayuda de dos sacerdotes cuando su hija de 13 años comienza a mostrar un comportamiento extraño y violento.",
        duration: 115,
        country: "United States",
        poster: "https://m.media-amazon.com/images/M/MV5BNWU2Y2JiYTktODMxYi00OTZlLWEyNjQtM2RiYjg3ZDY5YzZmXkEyXkFqcGdeQXVyMTYyNjA4MzQ@._V1_.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481607/trailers/lj6i2daebvzjypemoxzi.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481685/trailers/ffl00y1xeda7snkjfee8.mp4"
    },
    {
        name: "Destino Final V",
        director: "Steven Quale",
        genres: "Horror",
        description: "Un joven previene un terrible accidente en un puente colgante, sin saber que ha desafiado a la muerte. Ahora, él y los demás supervivientes deben luchar contra el destino para evitar una muerte aún más horrible.",
        duration: 132,
        country: "United States",
        poster: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjm-Xjwdhtf1E5uabkC64qld2zA7sCZHs3X7FdBnwwEraVS0hTB9N1FyvYvJDykWEYD6bdBqrljS074n3K62qFQBAZ6D0ho2pPTFAJtGxXYjCQVcXiEObJPhdyoiMTFfeLmz5e_8li5fu-H/s1600/destino-final-5-poster.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481607/trailers/lj6i2daebvzjypemoxzi.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481685/trailers/ffl00y1xeda7snkjfee8.mp4"
    },
    {
        name: "La Monja II",
        director: "Michael Chaves",
        genres: "Horror, Mystery",
        description: "En 1956, un sacerdote es asesinado en Rumanía y un mal se está extendiendo sin control. La hermana Irene, junto al padre Frenchie y un joven novicio, se enfrentan de nuevo a la monja demoníaca Valak.",
        duration: 132,
        country: "United States",
        poster: "https://image.tmdb.org/t/p/original/x0ryPlzZjpOojEAuGrre2lFuBv6.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481607/trailers/lj6i2daebvzjypemoxzi.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481685/trailers/ffl00y1xeda7snkjfee8.mp4"
    },
    {
        name: "Rápido y furioso: Reto Tokio",
        director: "Justin Lin",
        genres: "Action, Adventure",
        description: "Sean Boswell, un joven problemático, es enviado a Tokio a vivir con su padre militar. Allí se introduce en el mundo de las carreras callejeras de drift y se enfrenta al 'Rey del Drift', Takashi.",
        duration: 132,
        country: "United States",
        poster: "https://mx.web.img3.acsta.net/r_1280_720/medias/nmedia/18/36/31/38/18607308.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481607/trailers/lj6i2daebvzjypemoxzi.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481685/trailers/ffl00y1xeda7snkjfee8.mp4"
    },
    {
        name: "La Máscara del Zorro",
        director: "Martin Campbell",
        genres: "Action, Adventure, Romance",
        description: "Don Diego de la Vega, un noble español, es convertido en el Zorro, un justiciero enmascarado que lucha contra la tiranía del gobernador Montero en la California colonial española.",
        duration: 136,
        country: "United States",
        poster: "https://i.pinimg.com/736x/9b/10/2f/9b102f2374589814bd46cb78896a513f.jpg",
        trailer: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481607/trailers/lj6i2daebvzjypemoxzi.mp4",
        movie: "https://res.cloudinary.com/dtn2ewtqg/video/upload/v1711481685/trailers/ffl00y1xeda7snkjfee8.mp4"
    },
];

module.exports = sampleMovies;
